version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}@example.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8888:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  frontend:
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

  backend:
    platform: linux/amd64
    restart: unless-stopped
    mem_limit: 4g
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"

volumes:
  db:
    driver: local
  pgadmin:
